windows_exporter_version: "0.22.0"
windows_exporter_download_url: "https://github.com/prometheus-community/windows_exporter/releases/download/v{{ windows_exporter_version }}/windows_exporter-{{ windows_exporter_version }}-amd64.msi"
listen_port: 9090
collectors:
  - cpu
  - cs
  - logical_disk
  - memory
  - net
  - os
  - service
  - system